### ISSUE TITLE
Examples don't work on NekoVM

### ISSUE THREAD

**Issue by vroad** [away3d/away3d-examples-openfl#4]
Examples only worked with windows target.
With html5 and flash target it compiles, but cannot view them in Chrome.
Didn't work on IE and Firefox either.

windows:
Worked.

html5:
Lib.hx:114: Warning: Graphics.drawRoundRect is not implemented Basic_Fire.js:24077
Uncaught TypeError: Cannot set property '0' of undefined Basic_Fire.js:28463

Neko:
C:\HaxeToolkit\haxe\lib\away3d-examples\git\Basic_Particles>lime test neko
EventDispatcher.hx:28: WARNING: Weak listener not supported for native (using ha
rd reference)
EventDispatcher.hx:28: WARNING: Weak listener not supported for native (using ha
rd reference)
Invalid array access
Called from openfl/display3D/OpenFLStage3D.hx line 52
Called from away3d/core/managers/Stage3DManager.hx line 79
Called from away3d/core/managers/Stage3DManager.hx line 107
Called from away3d/containers/View3D.hx line 1143
Called from openfl/events/EventDispatcher.hx line 268
Called from openfl/events/EventDispatcher.hx line 98
Called from openfl/display/DisplayObject.hx line 194
Called from openfl/display/DisplayObject.hx line 71
Called from openfl/display/DisplayObject.hx line 374
Called from openfl/display/DisplayObjectContainer.hx line 373
Called from openfl/display/DisplayObject.hx line 435
Called from openfl/display/DisplayObjectContainer.hx line 31
Called from Basic_Particles.hx line 89
Called from ApplicationMain.hx line 193
Called from ApplicationMain.hx line 193
Called from C:\HaxeToolkit\haxe\std/neko/_std/Type.hx line 108
Called from ApplicationMain.hx line 95
Called from openfl/Lib.hx line 113

flash:
Nothing was shown.
In Basic_Fire example I could select a text saying "PLY:0".

**Comment by Greg209** [comment]
With the latest OpenFL/Lime and the new Away3D Neko builds now work again. Some of the examples are slow to load due to Neko implementation of the Vector class - needs looking into for performance enhancing
