### ISSUE TITLE
Basic_Skybox sample won't work on flash target

### ISSUE THREAD

**Issue by ViktorLajos** [away3d/away3d-examples-openfl#7]
I tryied the Basic_Skybox on cpp, and html5 targets, they work nice, but not on flash. It just show a black screen with a white rectangle: https://www.dropbox.com/s/di5hbzjmlhwbgoj/away3d-openfl-skybox-flash-issue.jpg?dl=0

**Comment by Greg209** [comment]
Skybox example now works on Flash target with latest OpenFL/Lime and Away3D
